//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIQTrainingSite {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HIQResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HIQResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HIQTrainingSite.HIQResources", typeof(HIQResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HIQ Training.
        /// </summary>
        public static string appName {
            get {
                return ResourceManager.GetString("appName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo.
        /// </summary>
        public static string buttonAdd {
            get {
                return ResourceManager.GetString("buttonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Certificação.
        /// </summary>
        public static string buttonAddCertification {
            get {
                return ResourceManager.GetString("buttonAddCertification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Formando Externo.
        /// </summary>
        public static string ButtonAddExternalStudent {
            get {
                return ResourceManager.GetString("ButtonAddExternalStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Inscrição Externa.
        /// </summary>
        public static string ButtonAddExternInscription {
            get {
                return ResourceManager.GetString("ButtonAddExternInscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Formador Externo.
        /// </summary>
        public static string ButtonAddExternTeacher {
            get {
                return ResourceManager.GetString("ButtonAddExternTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Inscrição Interna.
        /// </summary>
        public static string ButtonAddInternInscription {
            get {
                return ResourceManager.GetString("ButtonAddInternInscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Formando Interno.
        /// </summary>
        public static string ButtonAddInternStudent {
            get {
                return ResourceManager.GetString("ButtonAddInternStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Formador Interno.
        /// </summary>
        public static string ButtonAddInternTeacher {
            get {
                return ResourceManager.GetString("ButtonAddInternTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presenças.
        /// </summary>
        public static string buttonAttendance {
            get {
                return ResourceManager.GetString("buttonAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar.
        /// </summary>
        public static string buttonBack {
            get {
                return ResourceManager.GetString("buttonBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificações.
        /// </summary>
        public static string buttonCertifications {
            get {
                return ResourceManager.GetString("buttonCertifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar Password.
        /// </summary>
        public static string buttonChangePassword {
            get {
                return ResourceManager.GetString("buttonChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpar.
        /// </summary>
        public static string buttonClean {
            get {
                return ResourceManager.GetString("buttonClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar.
        /// </summary>
        public static string buttonConfirm {
            get {
                return ResourceManager.GetString("buttonConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formações.
        /// </summary>
        public static string buttonCourse {
            get {
                return ResourceManager.GetString("buttonCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formações dadas.
        /// </summary>
        public static string buttonCoursesTeached {
            get {
                return ResourceManager.GetString("buttonCoursesTeached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remover.
        /// </summary>
        public static string buttonDelete {
            get {
                return ResourceManager.GetString("buttonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhe.
        /// </summary>
        public static string buttonDetail {
            get {
                return ResourceManager.GetString("buttonDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string buttonEdit {
            get {
                return ResourceManager.GetString("buttonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Página Principal.
        /// </summary>
        public static string buttonHomePage {
            get {
                return ResourceManager.GetString("buttonHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string buttonSave {
            get {
                return ResourceManager.GetString("buttonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar.
        /// </summary>
        public static string buttonSearch {
            get {
                return ResourceManager.GetString("buttonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formandos.
        /// </summary>
        public static string buttonStudents {
            get {
                return ResourceManager.GetString("buttonStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Todos --.
        /// </summary>
        public static string dropdownAllOptions {
            get {
                return ResourceManager.GetString("dropdownAllOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ficheiro muito extenso. Maximo 2MB.
        /// </summary>
        public static string errorFileToLong {
            get {
                return ResourceManager.GetString("errorFileToLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email inválido..
        /// </summary>
        public static string errorInvalidEmail {
            get {
                return ResourceManager.GetString("errorInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo da data encontra-se vazio.
        /// </summary>
        public static string errorMessageDateEmpty {
            get {
                return ResourceManager.GetString("errorMessageDateEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome inserido já existe..
        /// </summary>
        public static string errorMessageDuplicateName {
            get {
                return ResourceManager.GetString("errorMessageDuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registo duplicado..
        /// </summary>
        public static string errorMessageDuplicateRecord {
            get {
                return ResourceManager.GetString("errorMessageDuplicateRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro. Não foi possivel executar a operação. Informe o administrador da aplicação..
        /// </summary>
        public static string errorMessageExceptionOccurred {
            get {
                return ResourceManager.GetString("errorMessageExceptionOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato de email incorreto..
        /// </summary>
        public static string errorMessageInvalidEmail {
            get {
                return ResourceManager.GetString("errorMessageInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insira o honorário.
        /// </summary>
        public static string errorMessageInvalidPayRoll {
            get {
                return ResourceManager.GetString("errorMessageInvalidPayRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de telefone inválido..
        /// </summary>
        public static string errorMessageInvalidPhoneNumber {
            get {
                return ResourceManager.GetString("errorMessageInvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} e {1} não são iguais..
        /// </summary>
        public static string errorMessagePasswordAndConfirmPasseordDontMatch {
            get {
                return ResourceManager.GetString("errorMessagePasswordAndConfirmPasseordDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo de preenchimento obrigatório.
        /// </summary>
        public static string errorMessageRequired {
            get {
                return ResourceManager.GetString("errorMessageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha em {0} no máximo {1} carateres..
        /// </summary>
        public static string errorMessageStringMaxLength {
            get {
                return ResourceManager.GetString("errorMessageStringMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha em {0} no máximo {1} carateres e no mínimo {2}..
        /// </summary>
        public static string errorMessageStringMaxMinLength {
            get {
                return ResourceManager.GetString("errorMessageStringMaxMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscrição repetida.
        /// </summary>
        public static string errorMessageStudentInscriptionAlreadyMade {
            get {
                return ResourceManager.GetString("errorMessageStudentInscriptionAlreadyMade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizador desconhecido.
        /// </summary>
        public static string errorMessageStudentNotFound {
            get {
                return ResourceManager.GetString("errorMessageStudentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizador desconhecido.
        /// </summary>
        public static string errorMessageTeacherNotFound {
            get {
                return ResourceManager.GetString("errorMessageTeacherNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível apagar o registo porque existem dependências..
        /// </summary>
        public static string errorMessageUnableToDeleteRecord {
            get {
                return ResourceManager.GetString("errorMessageUnableToDeleteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível executar a operação.
        /// </summary>
        public static string errorMessageUnableToExecuteOperation {
            get {
                return ResourceManager.GetString("errorMessageUnableToExecuteOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ação desconhecida..
        /// </summary>
        public static string errorMessageUnknownAction {
            get {
                return ResourceManager.GetString("errorMessageUnknownAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registo desconhecido.
        /// </summary>
        public static string errorMessageUnknownRecord {
            get {
                return ResourceManager.GetString("errorMessageUnknownRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizador desconhecido..
        /// </summary>
        public static string errorMessageUnknownUser {
            get {
                return ResourceManager.GetString("errorMessageUnknownUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ficheiro não é do tipo Excel.
        /// </summary>
        public static string errorNotExcel {
            get {
                return ResourceManager.GetString("errorNotExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A nota foi adicionada ao calendário..
        /// </summary>
        public static string eventAddConfirmed {
            get {
                return ResourceManager.GetString("eventAddConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A nota foi removida do calendário..
        /// </summary>
        public static string eventDeleteConfirmed {
            get {
                return ResourceManager.GetString("eventDeleteConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Formando já se encontra inscrito para essa data, pretende inscrever mesmo assim?.
        /// </summary>
        public static string genericQuestionAreYouSure {
            get {
                return ResourceManager.GetString("genericQuestionAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem a certeza que quer remover o registo?.
        /// </summary>
        public static string genericQuestionAreYouSureDelete {
            get {
                return ResourceManager.GetString("genericQuestionAreYouSureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privilégios da Aplicação.
        /// </summary>
        public static string labelApplicationRoles {
            get {
                return ResourceManager.GetString("labelApplicationRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presente.
        /// </summary>
        public static string labelAttended {
            get {
                return ResourceManager.GetString("labelAttended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelado.
        /// </summary>
        public static string labelCanceled {
            get {
                return ResourceManager.GetString("labelCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observacao cancelamento.
        /// </summary>
        public static string labelCanceledObservation {
            get {
                return ResourceManager.GetString("labelCanceledObservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificação.
        /// </summary>
        public static string labelCertification {
            get {
                return ResourceManager.GetString("labelCertification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da certificação.
        /// </summary>
        public static string labelCertificationName {
            get {
                return ResourceManager.GetString("labelCertificationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string labelCertificationStatus {
            get {
                return ResourceManager.GetString("labelCertificationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classificação.
        /// </summary>
        public static string labelClassification {
            get {
                return ResourceManager.GetString("labelClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de fim.
        /// </summary>
        public static string labelCloseDate {
            get {
                return ResourceManager.GetString("labelCloseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string labelCode {
            get {
                return ResourceManager.GetString("labelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa.
        /// </summary>
        public static string LabelCompany {
            get {
                return ResourceManager.GetString("LabelCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa.
        /// </summary>
        public static string labelCompanyName {
            get {
                return ResourceManager.GetString("labelCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendário.
        /// </summary>
        public static string labelCourseCalendar {
            get {
                return ResourceManager.GetString("labelCourseCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string labelCourseDate {
            get {
                return ResourceManager.GetString("labelCourseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nível.
        /// </summary>
        public static string labelCourseLevel {
            get {
                return ResourceManager.GetString("labelCourseLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string labelCourseLevelName {
            get {
                return ResourceManager.GetString("labelCourseLevelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string labelCourseLocationName {
            get {
                return ResourceManager.GetString("labelCourseLocationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string labelCourseName {
            get {
                return ResourceManager.GetString("labelCourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string labelCourseStatus {
            get {
                return ResourceManager.GetString("labelCourseStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string labelCourseType {
            get {
                return ResourceManager.GetString("labelCourseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de realização.
        /// </summary>
        public static string labelDate {
            get {
                return ResourceManager.GetString("labelDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cor da sala.
        /// </summary>
        public static string labelDisplayColor {
            get {
                return ResourceManager.GetString("labelDisplayColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dtp.
        /// </summary>
        public static string labelDtp {
            get {
                return ResourceManager.GetString("labelDtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carga horária.
        /// </summary>
        public static string labelEffort {
            get {
                return ResourceManager.GetString("labelEffort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string labelEmail {
            get {
                return ResourceManager.GetString("labelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora de fim.
        /// </summary>
        public static string labelEndHour {
            get {
                return ResourceManager.GetString("labelEndHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os ficheiros a importar deverão estar na directoria: C:\HIQTraining\ExcellImport.
        /// </summary>
        public static string labelExcellPath {
            get {
                return ResourceManager.GetString("labelExcellPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscrição externa.
        /// </summary>
        public static string labelExternInscription {
            get {
                return ResourceManager.GetString("labelExternInscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminado.
        /// </summary>
        public static string labelFinished {
            get {
                return ResourceManager.GetString("labelFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidade Formativa.
        /// </summary>
        public static string labelFormativeEntity {
            get {
                return ResourceManager.GetString("labelFormativeEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidade.
        /// </summary>
        public static string labelFormativeEntityName {
            get {
                return ResourceManager.GetString("labelFormativeEntityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Criação.
        /// </summary>
        public static string labelGenericCreatedDate {
            get {
                return ResourceManager.GetString("labelGenericCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Atualização.
        /// </summary>
        public static string labelGenericUpdatedDate {
            get {
                return ResourceManager.GetString("labelGenericUpdatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizador Criação.
        /// </summary>
        public static string labelGenericUserCreated {
            get {
                return ResourceManager.GetString("labelGenericUserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizador Atualização.
        /// </summary>
        public static string labelGenericUserUpdated {
            get {
                return ResourceManager.GetString("labelGenericUserUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado Inscrição.
        /// </summary>
        public static string labelInscriptionStatus {
            get {
                return ResourceManager.GetString("labelInscriptionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Inscrição.
        /// </summary>
        public static string labelInscriptionType {
            get {
                return ResourceManager.GetString("labelInscriptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Inscrição.
        /// </summary>
        public static string labelInscriptionTypeName {
            get {
                return ResourceManager.GetString("labelInscriptionTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        public static string labelLocation {
            get {
                return ResourceManager.GetString("labelLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string labelLocationName {
            get {
                return ResourceManager.GetString("labelLocationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscrição Duplicada!.
        /// </summary>
        public static string labelMultipleInscription {
            get {
                return ResourceManager.GetString("labelMultipleInscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Horas.
        /// </summary>
        public static string labelNumberHours {
            get {
                return ResourceManager.GetString("labelNumberHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observações.
        /// </summary>
        public static string labelObservations {
            get {
                return ResourceManager.GetString("labelObservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honorário.
        /// </summary>
        public static string labelPayRoll {
            get {
                return ResourceManager.GetString("labelPayRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ficheiro da certificação.
        /// </summary>
        public static string labelpdf {
            get {
                return ResourceManager.GetString("labelpdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone.
        /// </summary>
        public static string labelPhoneNumber {
            get {
                return ResourceManager.GetString("labelPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Área Técnica.
        /// </summary>
        public static string labelskills {
            get {
                return ResourceManager.GetString("labelskills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de início.
        /// </summary>
        public static string labelStartDate {
            get {
                return ResourceManager.GetString("labelStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora de início.
        /// </summary>
        public static string labelStartHour {
            get {
                return ResourceManager.GetString("labelStartHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do formando.
        /// </summary>
        public static string labelStudanteNameFull {
            get {
                return ResourceManager.GetString("labelStudanteNameFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificações de.
        /// </summary>
        public static string labelStudentCertifications {
            get {
                return ResourceManager.GetString("labelStudentCertifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string labelStudentName {
            get {
                return ResourceManager.GetString("labelStudentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string labelStudentStatus {
            get {
                return ResourceManager.GetString("labelStudentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formador.
        /// </summary>
        public static string labelTeacherName {
            get {
                return ResourceManager.GetString("labelTeacherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color do Utilizador.
        /// </summary>
        public static string LabelUserColor {
            get {
                return ResourceManager.GetString("LabelUserColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar Password.
        /// </summary>
        public static string labelUserConfirmPassword {
            get {
                return ResourceManager.GetString("labelUserConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string labelUserEmail {
            get {
                return ResourceManager.GetString("labelUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizador.
        /// </summary>
        public static string labelUserName {
            get {
                return ResourceManager.GetString("labelUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string labelUserPassword {
            get {
                return ResourceManager.GetString("labelUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privilégios do Utilizador.
        /// </summary>
        public static string labelUserRoles {
            get {
                return ResourceManager.GetString("labelUserRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Utilizador.
        /// </summary>
        public static string labelUserType {
            get {
                return ResourceManager.GetString("labelUserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inglês.
        /// </summary>
        public static string languageEN {
            get {
                return ResourceManager.GetString("languageEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Português.
        /// </summary>
        public static string languagePT {
            get {
                return ResourceManager.GetString("languagePT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tentativa de login falhou.
        /// </summary>
        public static string loginAttemptFailed {
            get {
                return ResourceManager.GetString("loginAttemptFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login falhou: A password inserida não está correcta.
        /// </summary>
        public static string loginFailedPassword {
            get {
                return ResourceManager.GetString("loginFailedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login falhou: Este nome de utilizador não existe.
        /// </summary>
        public static string loginFailedUser {
            get {
                return ResourceManager.GetString("loginFailedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administração.
        /// </summary>
        public static string menuAdministration {
            get {
                return ResourceManager.GetString("menuAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificações.
        /// </summary>
        public static string menuCertification {
            get {
                return ResourceManager.GetString("menuCertification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuração.
        /// </summary>
        public static string menuConfiguration {
            get {
                return ResourceManager.GetString("menuConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formações.
        /// </summary>
        public static string menuCourses {
            get {
                return ResourceManager.GetString("menuCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string menuLogin {
            get {
                return ResourceManager.GetString("menuLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registar.
        /// </summary>
        public static string menuRegister {
            get {
                return ResourceManager.GetString("menuRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estatísticas.
        /// </summary>
        public static string menuStatistics {
            get {
                return ResourceManager.GetString("menuStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro.
        /// </summary>
        public static string messageError {
            get {
                return ResourceManager.GetString("messageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação realizada com sucesso..
        /// </summary>
        public static string messageOperationSuccess {
            get {
                return ResourceManager.GetString("messageOperationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucesso.
        /// </summary>
        public static string messageSuccess {
            get {
                return ResourceManager.GetString("messageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procurar por Formação.
        /// </summary>
        public static string placeholderSearchCourse {
            get {
                return ResourceManager.GetString("placeholderSearchCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procurar por Formador.
        /// </summary>
        public static string placeholderSearchTeacher {
            get {
                return ResourceManager.GetString("placeholderSearchTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição da nota:.
        /// </summary>
        public static string questionEventAdd {
            get {
                return ResourceManager.GetString("questionEventAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja eliminar a nota ?.
        /// </summary>
        public static string questionEventDelete {
            get {
                return ResourceManager.GetString("questionEventDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presenças.
        /// </summary>
        public static string submenuAttendance {
            get {
                return ResourceManager.GetString("submenuAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendário.
        /// </summary>
        public static string submenuCalendar {
            get {
                return ResourceManager.GetString("submenuCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Área de Certificação.
        /// </summary>
        public static string submenuCertificationArea {
            get {
                return ResourceManager.GetString("submenuCertificationArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultado de certificação.
        /// </summary>
        public static string submenuCertificationResult {
            get {
                return ResourceManager.GetString("submenuCertificationResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresas.
        /// </summary>
        public static string submenuCompany {
            get {
                return ResourceManager.GetString("submenuCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscrições por empresa.
        /// </summary>
        public static string submenuCompanyStudents {
            get {
                return ResourceManager.GetString("submenuCompanyStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargas horárias por formação.
        /// </summary>
        public static string submenuCourseEffort {
            get {
                return ResourceManager.GetString("submenuCourseEffort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formações.
        /// </summary>
        public static string submenuCourses {
            get {
                return ResourceManager.GetString("submenuCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estatísticas de formação.
        /// </summary>
        public static string submenuCourseStatistics {
            get {
                return ResourceManager.GetString("submenuCourseStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipos de Formação.
        /// </summary>
        public static string submenuCourseType {
            get {
                return ResourceManager.GetString("submenuCourseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidades Formativas.
        /// </summary>
        public static string submenuFormativeEntities {
            get {
                return ResourceManager.GetString("submenuFormativeEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importação de Excell.
        /// </summary>
        public static string submenuImport {
            get {
                return ResourceManager.GetString("submenuImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscrições.
        /// </summary>
        public static string submenuInscription {
            get {
                return ResourceManager.GetString("submenuInscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipos de Inscrição.
        /// </summary>
        public static string submenuInscriptionTypes {
            get {
                return ResourceManager.GetString("submenuInscriptionTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Níveis de Formação.
        /// </summary>
        public static string submenuLevels {
            get {
                return ResourceManager.GetString("submenuLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salas de Formação.
        /// </summary>
        public static string submenuLocations {
            get {
                return ResourceManager.GetString("submenuLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscrições.
        /// </summary>
        public static string submenuStudentInscriptions {
            get {
                return ResourceManager.GetString("submenuStudentInscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formandos.
        /// </summary>
        public static string submenuStudents {
            get {
                return ResourceManager.GetString("submenuStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formadores.
        /// </summary>
        public static string submenuTeacher {
            get {
                return ResourceManager.GetString("submenuTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizadores.
        /// </summary>
        public static string submenuUsers {
            get {
                return ResourceManager.GetString("submenuUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registo removido com sucesso..
        /// </summary>
        public static string SuccessDeleted {
            get {
                return ResourceManager.GetString("SuccessDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registo atualizado com sucesso..
        /// </summary>
        public static string SuccessUpdated {
            get {
                return ResourceManager.GetString("SuccessUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo.
        /// </summary>
        public static string titleAdd {
            get {
                return ResourceManager.GetString("titleAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nota.
        /// </summary>
        public static string titleAddEditNote {
            get {
                return ResourceManager.GetString("titleAddEditNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Presenças.
        /// </summary>
        public static string titleAttendanceList {
            get {
                return ResourceManager.GetString("titleAttendanceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendário das formações.
        /// </summary>
        public static string titleCalendarList {
            get {
                return ResourceManager.GetString("titleCalendarList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de certificações.
        /// </summary>
        public static string titleCertificationList {
            get {
                return ResourceManager.GetString("titleCertificationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificações.
        /// </summary>
        public static string titleCertificationType {
            get {
                return ResourceManager.GetString("titleCertificationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Certificações.
        /// </summary>
        public static string titleCertificationTypeList {
            get {
                return ResourceManager.GetString("titleCertificationTypeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nível de Formação.
        /// </summary>
        public static string titleCourseLevel {
            get {
                return ResourceManager.GetString("titleCourseLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Níveis de Formação.
        /// </summary>
        public static string titleCourseLevelList {
            get {
                return ResourceManager.GetString("titleCourseLevelList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Formações.
        /// </summary>
        public static string titleCourseList {
            get {
                return ResourceManager.GetString("titleCourseList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sala de Formação.
        /// </summary>
        public static string titleCourseLocation {
            get {
                return ResourceManager.GetString("titleCourseLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Salas de Formação.
        /// </summary>
        public static string titleCourseLocationList {
            get {
                return ResourceManager.GetString("titleCourseLocationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Formação.
        /// </summary>
        public static string titleCourseType {
            get {
                return ResourceManager.GetString("titleCourseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipos de Formações.
        /// </summary>
        public static string titleCourseTypeList {
            get {
                return ResourceManager.GetString("titleCourseTypeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remover.
        /// </summary>
        public static string titleDelete {
            get {
                return ResourceManager.GetString("titleDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remover Nota.
        /// </summary>
        public static string titleDeleteNote {
            get {
                return ResourceManager.GetString("titleDeleteNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhe.
        /// </summary>
        public static string titleDetail {
            get {
                return ResourceManager.GetString("titleDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string titleEdit {
            get {
                return ResourceManager.GetString("titleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um Erro.
        /// </summary>
        public static string titleError {
            get {
                return ResourceManager.GetString("titleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Entidades Formativas.
        /// </summary>
        public static string titleFormativeEntitiesList {
            get {
                return ResourceManager.GetString("titleFormativeEntitiesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidade Formativa.
        /// </summary>
        public static string titleFormativeEntity {
            get {
                return ResourceManager.GetString("titleFormativeEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olá.
        /// </summary>
        public static string titleHello {
            get {
                return ResourceManager.GetString("titleHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importação de Excell.
        /// </summary>
        public static string titleImport {
            get {
                return ResourceManager.GetString("titleImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscrição.
        /// </summary>
        public static string titleInscription {
            get {
                return ResourceManager.GetString("titleInscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Inscrições.
        /// </summary>
        public static string titleInscriptionList {
            get {
                return ResourceManager.GetString("titleInscriptionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipos de inscrições.
        /// </summary>
        public static string titleInscriptionType {
            get {
                return ResourceManager.GetString("titleInscriptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de tipos de inscrições.
        /// </summary>
        public static string titleInscriptionTypeList {
            get {
                return ResourceManager.GetString("titleInscriptionTypeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sair Sessão.
        /// </summary>
        public static string titleLogOff {
            get {
                return ResourceManager.GetString("titleLogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operações.
        /// </summary>
        public static string titleOperations {
            get {
                return ResourceManager.GetString("titleOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione os privilégios do utilizador:.
        /// </summary>
        public static string titleSelectUserRoles {
            get {
                return ResourceManager.GetString("titleSelectUserRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formando.
        /// </summary>
        public static string titleStudent {
            get {
                return ResourceManager.GetString("titleStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Formandos.
        /// </summary>
        public static string titleStudentList {
            get {
                return ResourceManager.GetString("titleStudentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formadores.
        /// </summary>
        public static string titleTeacher {
            get {
                return ResourceManager.GetString("titleTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Formadores.
        /// </summary>
        public static string titleTeacherList {
            get {
                return ResourceManager.GetString("titleTeacherList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizador.
        /// </summary>
        public static string titleUser {
            get {
                return ResourceManager.GetString("titleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Utilizadores.
        /// </summary>
        public static string titleUsersList {
            get {
                return ResourceManager.GetString("titleUsersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presenças.
        /// </summary>
        public static string titlevalidationMessage {
            get {
                return ResourceManager.GetString("titlevalidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to certificação.
        /// </summary>
        public static string validationCertification {
            get {
                return ResourceManager.GetString("validationCertification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O código inserido já se encontra associado a outra {0}..
        /// </summary>
        public static string validationCode {
            get {
                return ResourceManager.GetString("validationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to formação.
        /// </summary>
        public static string validationCourse {
            get {
                return ResourceManager.GetString("validationCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este curso tem que ser calendarizado.
        /// </summary>
        public static string validationPresence {
            get {
                return ResourceManager.GetString("validationPresence", resourceCulture);
            }
        }
    }
}
