//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIQTraining.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int Id { get; set; }
        public int InscriptionId { get; set; }
        public int CalendarId { get; set; }
        public int Status { get; set; }
        public string Observation { get; set; }
        public string UserCreated { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UserUpdated { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual Calendar Calendar { get; set; }
        public virtual Inscription Inscription { get; set; }
    }
}
