//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIQTraining.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certification
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Classification { get; set; }
        public int CertificationTypeId { get; set; }
        public int Status { get; set; }
        public int StudentId { get; set; }
        public System.DateTime Date { get; set; }
        public string Observation { get; set; }
        public int FormativeEntityId { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UserCreated { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UserUpdated { get; set; }
        public string pdf { get; set; }
    
        public virtual CertificationType CertificationType { get; set; }
        public virtual FormativeEntity FormativeEntity { get; set; }
        public virtual Student Student { get; set; }
    }
}
