//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIQTraining.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.Calendars = new HashSet<Calendar>();
            this.Inscriptions = new HashSet<Inscription>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int LevelId { get; set; }
        public string Code { get; set; }
        public int LocationId { get; set; }
        public int FormativeEntityId { get; set; }
        public int TeacherId { get; set; }
        public string Observation { get; set; }
        public System.TimeSpan StartHour { get; set; }
        public int Status { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.TimeSpan EndHour { get; set; }
        public System.DateTime CloseDate { get; set; }
        public int InscriptionEmail { get; set; }
        public int ConfirmationEmail { get; set; }
        public int Reminder { get; set; }
        public int Documentation { get; set; }
        public int Intranet { get; set; }
        public int Material { get; set; }
        public int Dtp { get; set; }
        public int Certificates { get; set; }
        public int Avaliation { get; set; }
        public int Confidential { get; set; }
        public int UniqueReport { get; set; }
        public string UserCreated { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UserUpdated { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string CanceledObservation { get; set; }
        public string Effort { get; set; }
        public int CourseTypeId { get; set; }
        public string PayRoll { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Calendar> Calendars { get; set; }
        public virtual CourseLevel CourseLevel { get; set; }
        public virtual CourseLocation CourseLocation { get; set; }
        public virtual FormativeEntity FormativeEntity { get; set; }
        public virtual Teacher Teacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inscription> Inscriptions { get; set; }
        public virtual CourseType CourseType { get; set; }
    }
}
