//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIQTraining.LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HIQResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HIQResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HIQTraining.LocalResources.HIQResource", typeof(HIQResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Todos --.
        /// </summary>
        public static string dropdownAllOptions {
            get {
                return ResourceManager.GetString("dropdownAllOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível cancelar a inscrição porque o curso já teve inicio..
        /// </summary>
        public static string errorMessageCanNotCancelInscription {
            get {
                return ResourceManager.GetString("errorMessageCanNotCancelInscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha em {0} no máximo {1} carateres..
        /// </summary>
        public static string errorMessageStringMaxLength {
            get {
                return ResourceManager.GetString("errorMessageStringMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe o registo do formando.
        /// </summary>
        public static string errorMessageStudentAlreadyExists {
            get {
                return ResourceManager.GetString("errorMessageStudentAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscrição do aluno é repetida..
        /// </summary>
        public static string errorMessageStudentInscriptionAlreadyMade {
            get {
                return ResourceManager.GetString("errorMessageStudentInscriptionAlreadyMade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizador desconhecido.
        /// </summary>
        public static string errorMessageStudentNotFound {
            get {
                return ResourceManager.GetString("errorMessageStudentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe o registo do formador..
        /// </summary>
        public static string errorMessageTeacherAlreadyExists {
            get {
                return ResourceManager.GetString("errorMessageTeacherAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formador desconhecido.
        /// </summary>
        public static string errorMessageTeacherNotFound {
            get {
                return ResourceManager.GetString("errorMessageTeacherNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registo desconhecido.
        /// </summary>
        public static string errorMessageUnknownRecord {
            get {
                return ResourceManager.GetString("errorMessageUnknownRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizador desconhecido.
        /// </summary>
        public static string errorMessageUserNotFound {
            get {
                return ResourceManager.GetString("errorMessageUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observações.
        /// </summary>
        public static string labelObservations {
            get {
                return ResourceManager.GetString("labelObservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falta.
        /// </summary>
        public static string statusAttendance_0 {
            get {
                return ResourceManager.GetString("statusAttendance_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presente.
        /// </summary>
        public static string statusAttendance_1 {
            get {
                return ResourceManager.GetString("statusAttendance_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falta Justificada.
        /// </summary>
        public static string statusAttendance_2 {
            get {
                return ResourceManager.GetString("statusAttendance_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelada.
        /// </summary>
        public static string statusCalendar_0 {
            get {
                return ResourceManager.GetString("statusCalendar_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agendada.
        /// </summary>
        public static string statusCalendar_1 {
            get {
                return ResourceManager.GetString("statusCalendar_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprovado.
        /// </summary>
        public static string statusCertification_0 {
            get {
                return ResourceManager.GetString("statusCertification_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprovado.
        /// </summary>
        public static string statusCertification_1 {
            get {
                return ResourceManager.GetString("statusCertification_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por Iniciar.
        /// </summary>
        public static string statusCourse_0 {
            get {
                return ResourceManager.GetString("statusCourse_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A decorrer.
        /// </summary>
        public static string statusCourse_1 {
            get {
                return ResourceManager.GetString("statusCourse_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concluído.
        /// </summary>
        public static string statusCourse_2 {
            get {
                return ResourceManager.GetString("statusCourse_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelada.
        /// </summary>
        public static string statusCourse_3 {
            get {
                return ResourceManager.GetString("statusCourse_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscrito.
        /// </summary>
        public static string statusInscription_0 {
            get {
                return ResourceManager.GetString("statusInscription_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelado.
        /// </summary>
        public static string statusInscription_1 {
            get {
                return ResourceManager.GetString("statusInscription_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desistência.
        /// </summary>
        public static string statusInscription_2 {
            get {
                return ResourceManager.GetString("statusInscription_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inativo.
        /// </summary>
        public static string statusStudent_0 {
            get {
                return ResourceManager.GetString("statusStudent_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativo.
        /// </summary>
        public static string statusStudent_1 {
            get {
                return ResourceManager.GetString("statusStudent_1", resourceCulture);
            }
        }
    }
}
